@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< Updated upstream:RetryOtter333 - Copy/RetryOtter333/RetryOtter333.sim/sim_1/behav/xsim/compile.bat
REM Generated by Vivado on Tue May 14 13:11:01 -0700 2024
=======
REM Generated by Vivado on Thu May 16 20:04:05 -0700 2024
>>>>>>> Stashed changes:RetryOtter333/RetryOtter333.sim/sim_1/behav/xsim/compile.bat
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: compile.bat
REM
REM ****************************************************************************
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -prj Pipeline_Otter_tb_vlog.prj"
call xvlog  --incr --relax -L uvm -prj Pipeline_Otter_tb_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
