@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< Updated upstream:RetryOtter333 - Copy/RetryOtter333/RetryOtter333.sim/sim_1/behav/xsim/simulate.bat
REM Generated by Vivado on Tue May 14 13:11:26 -0700 2024
=======
REM Generated by Vivado on Thu May 16 20:04:19 -0700 2024
>>>>>>> Stashed changes:RetryOtter333/RetryOtter333.sim/sim_1/behav/xsim/simulate.bat
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
<<<<<<< Updated upstream:RetryOtter333 - Copy/RetryOtter333/RetryOtter333.sim/sim_1/behav/xsim/simulate.bat
echo "xsim Pipeline_Otter_tb_behav -key {Behavioral:sim_1:Functional:Pipeline_Otter_tb} -tclbatch Pipeline_Otter_tb.tcl -view Z:/Desktop/CPE333/RetryOtter333 - Copy/RetryOtter333/Pipeline_Otter_tb_behav.wcfg -log simulate.log"
call xsim  Pipeline_Otter_tb_behav -key {Behavioral:sim_1:Functional:Pipeline_Otter_tb} -tclbatch Pipeline_Otter_tb.tcl -view Z:/Desktop/CPE333/RetryOtter333 - Copy/RetryOtter333/Pipeline_Otter_tb_behav.wcfg -log simulate.log
=======
echo "xsim Pipeline_Otter_tb_behav -key {Behavioral:sim_1:Functional:Pipeline_Otter_tb} -tclbatch Pipeline_Otter_tb.tcl -view Z:/Desktop/CPE333/RetryOtter333/Pipeline_Otter_tb_behav.wcfg -log simulate.log"
call xsim  Pipeline_Otter_tb_behav -key {Behavioral:sim_1:Functional:Pipeline_Otter_tb} -tclbatch Pipeline_Otter_tb.tcl -view Z:/Desktop/CPE333/RetryOtter333/Pipeline_Otter_tb_behav.wcfg -log simulate.log
>>>>>>> Stashed changes:RetryOtter333/RetryOtter333.sim/sim_1/behav/xsim/simulate.bat
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
