@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon May 20 18:40:01 -0700 2024
REM SW Build 3900603 on Fri Jun 16 19:31:24 MDT 2023
REM
REM IP Build 3900379 on Sat Jun 17 05:28:05 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Pipeline_Otter_tb_behav -key {Behavioral:sim_1:Functional:Pipeline_Otter_tb} -tclbatch Pipeline_Otter_tb.tcl -view Z:/Documents/git/CPE333/RetryOtter333/Pipeline_Otter_tb_behav.wcfg -log simulate.log"
call xsim  Pipeline_Otter_tb_behav -key {Behavioral:sim_1:Functional:Pipeline_Otter_tb} -tclbatch Pipeline_Otter_tb.tcl -view Z:/Documents/git/CPE333/RetryOtter333/Pipeline_Otter_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
