@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon May 13 16:31:54 -0700 2024
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim otter_mcu_pipeline_testbench_behav -key {Behavioral:sim_1:Functional:otter_mcu_pipeline_testbench} -tclbatch otter_mcu_pipeline_testbench.tcl -log simulate.log"
call xsim  otter_mcu_pipeline_testbench_behav -key {Behavioral:sim_1:Functional:otter_mcu_pipeline_testbench} -tclbatch otter_mcu_pipeline_testbench.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
